- name: Enable non-free repository
  apt_repository:
    repo: deb http://ftp.se.debian.org/debian/ stretch main non-free
  become: yes

- name: install required packages
  package:
    name: "{{ item }}"
    state: present
    update_cache: yes
  with_items:
    - conserver-client
  become: yes

- name: create console.cf file
  template:
    src: templates/console.cf.j2
    dest: /etc/conserver/console.cf
    owner: root
    group: root
    mode: 0644
  become: yes

