- name: install required packages
  package:
    name: "{{ item }}"
    state: present
  with_items:
    - conserver-client
  become: yes

- name: create console.cf file
  template:
    src: console.cf.j2
    dest: /etc/console.cf
    owner: root
    group: root
    mode: 0644
  become: yes
